### ISSUE TITLE
Add a free Kanji mnemonics list to japanese language learning resource list

### ISSUE THREAD

**Issue by carlospazuzu** [wotakumoe/wotaku#69]
There is website with a list of mnemonics for all 2136 Joyo kanji called [Ulrike's Mnemonics](https://www.joyokanji.com/ulrikes-mnemonics), which is by far the most efficient way to learn kanji. But the website is really old and slow, so I scrapped their data and created a web app with a list of all kanji and with a better search system.

It's been really useful for me and I think it would be a great addition to wotaku resource list.

You can see the app live here [Ulrike's Mnemonics Improved](https://japanesestudies.github.io/ulrikes-mnemonics/).

**Comment by Memenami** [comment]
Added, thanks for sharing!
