### ISSUE TITLE
Request to add Globie to the Misc -> Socials section

### ISSUE THREAD

**Issue by Pyrospower** [wotakumoe/wotaku#70]
Hi! I would like to suggest adding the VTuber agency [Globie](https://globie.net) to your index under the [Misc -> Socials](https://wotaku.wiki/misc#socials) section. 

Useful links:
- [Twitter](https://x.com/globiesocial)
- [Reddit](https://www.reddit.com/user/globie-official)
- [YouTube](https://www.youtube.com/@globieofficial)

**Comment by woducku** [comment]
why does brave group own so many shit. everywhere i go i see brave group.
