### ISSUE TITLE
Add animerealms.org

### ISSUE THREAD

**Issue by xenmods** [wotakumoe/wotaku#75]
It is an ad-free streaming website with:
- In built AniList tracking support.
- It scrapes multiple websites: zoro & gogo (more will be added soon).
- Has a nice interface with a minimal UI
- Has disqus comments
- Clean and simple player

Link: https://animerealms.org/

**Comment by woducku** [comment]
Added. But fix ur seasons tab. It works for normal shows. but for weekly shows it will mess up. i dont think the api was made for 4 cour shows like these. Also naruto one was completely wrong (u r probably using the "related" data or the api source is dumb.)

![image](https://github.com/user-attachments/assets/d3f905db-626a-4403-aa3f-55c1f8b73431)

![image](https://github.com/user-attachments/assets/9f567379-9056-4dab-bd09-7395b78b4125)

![image](https://github.com/user-attachments/assets/54958dfd-a745-40b3-8bc4-3d629efab324)
