### ISSUE TITLE
Docs: More info on `partial seeding bad for file retention`

### ISSUE THREAD

**Issue by KAGEYAM4** [wotakumoe/wotaku#80]
https://github.com/wotakumoe/wotaku/blob/bfa60ca9174ef10e428a72cf37d9cef2c8d7a6b5/docs/glossary/torrent.md?plain=1#L20

Can you please add more info on what is meant by `bad for file retention`.

**Comment by Memenami** [comment]
It's in the name. If it's partial, it's not complete. There's no complete copy of the torrent.
