### ISSUE TITLE
Add an image next to the "Wotaku" (GitHub site)

### ISSUE THREAD

**Issue by kvhjdffv** [wotakumoe/wotaku#82]
Steps to reproduce:
![2024-11-05 21_14_05-wotakumoe_wotaku_ An otaku index for everything! - Brave](https://github.com/user-attachments/assets/fcdff917-0441-4727-917a-a5ad9558d46e)
*(Click on the Deployments tab at the right-hand side of the screen)*

![2024-11-05 21_14_17-Deployments · wotakumoe_wotaku - Brave](https://github.com/user-attachments/assets/e7423af1-450f-4f2d-87ff-017dd22a1fc8)
*(Click on the link)*

![2024-11-05 21_14_32-Wotaku _ wotaku - Brave](https://github.com/user-attachments/assets/eb521a40-018a-472c-a46e-b48c0286cf5c)
*(There isn't an image next to the "Wotaku")*

**Comment by woducku** [comment]
![README](https://github.com/user-attachments/assets/0f2a258f-4bca-4423-b8d0-ecbb23fb383b)

**Comment by taskylizard** [comment]
This is not an officially supported pager, please don't open an open ticket for this.
