### ISSUE TITLE
There's a slight delay in Takodachi whenever I change any type of display setting in the wiki

### ISSUE THREAD

**Issue by kvhjdffv** [wotakumoe/wotaku#85]
https://github.com/user-attachments/assets/8108ce5f-4355-41af-936d-bbe420711848

**Comment by Memenami** [comment]
Can you like get a life?

**Comment by taskylizard** [comment]
Display settings aren't controlled by us, nothing to fix. Besides that, it's for accessiblity needs, not meant as a regular text zoom, and you won't want the takodachi enabled anyway in that case.

Please do not open unnecessary issue threads.
