### ISSUE TITLE
Add Anime-Stream.io

### ISSUE THREAD

**Issue by AquaHoshinoGoat** [wotakumoe/wotaku#91]
https://anime-stream.io - Full HD streams with quality options, downloads for new episodes, minimal ads (2 popups), no site ads, fast loading, and secure offshore servers!

**Comment by Memenami** [comment]
We aren't adding more scrapers atm.

**Comment by AquaHoshinoGoat** [comment]
The new Episodes are not scrapped since 3-4 Weeks, every day it is manually
downloaded, encoded, uploaded and linked

Memenami ***@***.***> schrieb am So. 22. Dez. 2024 um 11:17:
